name: Suggestion
description: Suggérer quelque chose qui améliorerait le pack de ressource
labels: [ "Suggestion" ]
body:
    -   type: textarea
        attributes:
            label: Décrivez la suggestion
            description: Que devrions-nous ajouter ou modifier pour améliorer le pack.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Captures d'écran et vidéos
            description: Si possible, ajoutez des captures d'écran et vidéos pour aider à expliquer votre suggestion.
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Information supplémentaire
            description: Ajoutez ici tout autre information concernant votre suggestion.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Merci d'avoir pris le temps de proposer une suggestion et d'aider à améliorer le pack de ressources!"
